apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Automation
  annotations:
    harness.io/pipelines: |
      Uber-Automation: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/QE_Team/projects/Quality_Assurence/pipelines/Uber_Pipeline/pipeline-studio?storeType=INLINE
    grafana/dashboard-selector: "http://35.247.91.252/d/RpSjVqWMz/redis-memstore?orgId=1"
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
