apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: harness-srm2
  annotations:
    harness.io/services: |
      order prod: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/cvng/projects/ecommerce/services/Order
      test qa: https://qa.harness.io/ng/account/-k53qRQAQ1O7DBLb9ACnjQ/home/orgs/Flipkart/projects/ecommerce/services/Test
    grafana/dashboard-selector: "http://35.247.91.252/d/RpSjVqWMz/redis-memstore?orgId=1"
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]