kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: Abhishek
apiVersion: backstage.io/v1alpha1
metadata:
  name: Github-2
  tags: []
  annotations:
    harness.io/cd-serviceId: Github
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/deafult/projects/Abhishek/details
